server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.web: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
        
spring:
  mail:
    default-encoding: UTF-8
    host: localhost
    port: 25
    from: kumarsaurabh2006@gmail.com
    properties:
      mail:
        smtp:
          auth: false
