server:
  port: 8881

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.web: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
   cloud:
    config:
      server:
        git:
          uri: https://github.com/ksaurabh1981/sample-config-properties.git
          skipSslValidation: true
